title: lama
description: accès en 1 clic aux ressources des bibliothèques de l'Université d'Aix-Marseille
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
