title: lama addons
description: extensions de navigateur pour activer l'accès aux ressources documentaires AMU
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
